branches:
  - master

  - name: staging
    prerelease: beta

  - name: development
    prerelease: dev



plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/changelog"
  -
    - "@semantic-release/npm"
    - npmPublish: false
  - "@semantic-release/github"
  - "@semantic-release/git"

