name: Create release

on:
  push:
    branches:
      - master
      - staging
      - development

jobs:
  release:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-semantic-release

      - name: Install dependencies
        run: npm install --force

      - name: Release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_SEMANTIC_RELEASE }}
